### ISSUE TITLE
Feature Request: Add more documentation about `syncHashedEmail`

### ISSUE THREAD

**Issue by Aarbel** [OneSignal/OneSignal-Cordova-Example#7]
https://github.com/OneSignal/OneSignal-Cordova-Example/blob/9cffbbd6399899d5c25752f83fe8afca17e10137/www/js/index.js#L93-L95

`syncHashedEmail` is documented nowhere, what's exactly the goal of this method ? 

Thanks ;)

**Comment by jkasten2** [comment]
`syncHashedEmail` is deprecated, please use `setEmail` instead.
https://documentation.onesignal.com/docs/cordova-sdk#section-set-email
